bumps pygit2 dependency from 1.16.0 to 1.19.0 / linux hook install fix (#12339)
# About the pull request

current version of pygit2 specified in requirements relies on a
dependency that is no longer available (on mine and vending's package
manager anyway); bumping the requirement resolves this

should allow installing the hooks out of the box-- if a different
version of pygit would be better (between 1.16 and 1.19) lmk I know
nothing about the python ecosystem but 19 is the latest in my package
manager


# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

before change
```sh
❯ ./tools/hooks/install.sh
Updating dependencies...
Requirement already satisfied: wheel in ./tools/bootstrap/.cache/venv/lib/python3.14/site-packages (0.47.0)
Requirement already satisfied: packaging>=24.0 in ./tools/bootstrap/.cache/venv/lib/python3.14/site-packages (from wheel) (26.2)
Requirement already satisfied: pip in ./tools/bootstrap/.cache/venv/lib/python3.14/site-packages (26.1.1)
Collecting pygit2==1.16.0 (from -r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 1))
  Using cached pygit2-1.16.0.tar.gz (768 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bidict==0.22.0 (from -r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 2))
  Using cached bidict-0.22.0-py3-none-any.whl.metadata (9.2 kB)
Collecting Pillow==11.0.0 (from -r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 3))
  Using cached pillow-11.0.0-cp314-cp314-linux_x86_64.whl
Collecting PyYaml==6.0.1 (from -r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 6))
  Using cached pyyaml-6.0.1-cp314-cp314-linux_x86_64.whl
Collecting beautifulsoup4==4.9.3 (from -r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 7))
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl.metadata (4.2 kB)
Collecting cffi>=1.17.0 (from pygit2==1.16.0->-r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 1))
  Using cached cffi-2.0.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.6 kB)
Collecting soupsieve>1.2 (from beautifulsoup4==4.9.3->-r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 7))
  Using cached soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Collecting pycparser (from cffi>=1.17.0->pygit2==1.16.0->-r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 1))
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Using cached bidict-0.22.0-py3-none-any.whl (36 kB)
Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Using cached cffi-2.0.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (219 kB)
Using cached soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Building wheels for collected packages: pygit2
  Building wheel for pygit2 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pygit2 (pyproject.toml) did not run successfully.
  │ exit code: 1

```

after changes
```sh
❯ ./tools/hooks/install.sh
Updating dependencies...
Requirement already satisfied: wheel in ./tools/bootstrap/.cache/venv/lib/python3.14/site-packages (0.47.0)
Requirement already satisfied: packaging>=24.0 in ./tools/bootstrap/.cache/venv/lib/python3.14/site-packages (from wheel) (26.2)
Requirement already satisfied: pip in ./tools/bootstrap/.cache/venv/lib/python3.14/site-packages (26.1.1)
Collecting pygit2==1.19.0 (from -r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 1))
  Downloading pygit2-1.19.0-cp314-cp314-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting bidict==0.22.0 (from -r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 2))
  Using cached bidict-0.22.0-py3-none-any.whl.metadata (9.2 kB)
Collecting Pillow==11.0.0 (from -r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 3))
  Using cached pillow-11.0.0-cp314-cp314-linux_x86_64.whl
Collecting PyYaml==6.0.1 (from -r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 6))
  Using cached pyyaml-6.0.1-cp314-cp314-linux_x86_64.whl
Collecting beautifulsoup4==4.9.3 (from -r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 7))
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl.metadata (4.2 kB)
Collecting cffi>=2.0 (from pygit2==1.19.0->-r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 1))
  Using cached cffi-2.0.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.6 kB)
Collecting soupsieve>1.2 (from beautifulsoup4==4.9.3->-r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 7))
  Using cached soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Collecting pycparser (from cffi>=2.0->pygit2==1.19.0->-r /home/freya/Documents/repositories/ss13/cmss13/tools/hooks/../requirements.txt (line 1))
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Downloading pygit2-1.19.0-cp314-cp314-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 3.3 MB/s  0:00:01
Using cached bidict-0.22.0-py3-none-any.whl (36 kB)
Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Using cached cffi-2.0.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (219 kB)
Using cached soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: soupsieve, PyYaml, pycparser, Pillow, bidict, cffi, beautifulsoup4, pygit2
Successfully installed Pillow-11.0.0 PyYaml-6.0.1 beautifulsoup4-4.9.3 bidict-0.22.0 cffi-2.0.0 pycparser-3.0 pygit2-1.19.0 soupsieve-2.8.4
---
Installing hook: pre-commit
Installing merge driver: dmm
Installing merge driver: dmi

```

</details>


# Changelog

no player changes